"""Canonical high-level-to-low-level ordering for the TT-Metal reports."""

from __future__ import annotations


LAYERS = (
    {
        "number": 0,
        "slug": "orientation",
        "title": "Orientation and stack",
        "abstraction": "Whole stack",
        "focus": "Vocabulary, boundaries, and the TT-NN to hardware mental model.",
        "start_when": "you are new to Tenstorrent or cannot yet place TT-NN, TT-Metalium, kernels, and Tensix on one diagram",
        "guide": "level-0-orientation.md",
        "architect_task": "Locate the first broken contract and assign the problem to the layer that owns it.",
        "reasoning_path": "symptom → invariant → owning layer → evidence above/below → one change → original metric",
        "decision": "Which layer owns the first violated invariant?",
        "mechanism": "A contract map from model semantics through TT-NN, runtime, kernels, and hardware.",
        "benefit": "The investigation starts with a bounded hypothesis instead of an ISA-sized search space.",
        "cost": "Layering hides detail, so identity must be carried across traces and profiles.",
        "evidence": "Trace one operator across every boundary and name the object, owner, invariant, and measurement at each handoff.",
        "paths": (
            "ttnn/ttnn.md",
        ),
    },
    {
        "number": 1,
        "slug": "models-operators",
        "title": "Models and operators",
        "abstraction": "Highest",
        "focus": "See how complete workloads and operators use TT-NN.",
        "start_when": "you can name the major stack layers and want an application-level reason for the lower-level machinery",
        "guide": "level-1-models-operators.md",
        "architect_task": "Partition the graph so accuracy is preserved while movement, fallback, and repeated work are minimized.",
        "reasoning_path": "workload distribution → tensor lifetimes → fusion/residency choices → accuracy budget → end-to-end validation",
        "decision": "Where should the model graph be split, specialized, fused, or kept resident?",
        "mechanism": "Operator variants and graph boundaries chosen from tensor lifetime, reuse, and workload regime.",
        "benefit": "Useful model work reaches the accelerator without paying avoidable conversion, transfer, or materialization costs.",
        "cost": "More specialization increases program variants, validation surface, and resident-state pressure.",
        "evidence": "A production shape histogram, subgraph byte/lifetime model, module-level golden checks, and end-to-end latency split by regime.",
        "paths": (
            "ttnn/TTNN-model-bringup.md",
            "CNNs/ttcnn.md",
            "CNNs/cnn_optimizations.md",
            "LLMs/llms.md",
            "LLMs/vLLM_integration.md",
            "FlashAttention/FlashAttention.md",
            "FlashAttention/FlashDecode.md",
            "ttnn_operators/intimg.md",
            "ViT-TTNN/vit.md",
            "ViT-TTNN/vit_bh.md",
            "YoloV4-TTNN/yolov4.md",
        ),
    },
    {
        "number": 2,
        "slug": "ttnn-runtime",
        "title": "TT-NN runtime and observability",
        "abstraction": "High",
        "focus": "Devices, tracing, comparison, serialization, and runtime behavior.",
        "start_when": "you understand what an operator does and now need to see how TT-NN schedules, records, and checks it",
        "guide": "level-2-runtime-observability.md",
        "architect_task": "Preserve identity, lifetime, and order while removing construction and submission overhead.",
        "reasoning_path": "cold/warm/replay split → cache identity → queue ownership → trace structure + profile time → comparison",
        "decision": "What state is reusable, what is runtime-patchable, and what must be ordered explicitly?",
        "mechanism": "Programs, queues, traces, sub-devices, serialization, and observability keyed by stable identity and lifetime.",
        "benefit": "Compilation and host submission are amortized while repeated execution remains correct and explainable.",
        "cost": "Cached and asynchronous paths create stricter address, ownership, version, and event invariants.",
        "evidence": "Cold/warm/replay distributions joined to operation identity, queue events, trace structure, and a numerical reference.",
        "paths": (
            "SubDevices/SubDevices.md",
            "tensor_serialization/tensor_serialization.md",
            "ttnn/graph-tracing.md",
            "ttnn/operation-tracing.md",
            "ttnn/comparison-mode.md",
        ),
    },
    {
        "number": 3,
        "slug": "tensor-memory",
        "title": "Tensor representation and memory",
        "abstraction": "Middle",
        "focus": "Tiles, formats, layouts, sharding, allocation, and addressing.",
        "start_when": "you can follow an operator call but cannot yet predict where its bytes live or how a kernel addresses them",
        "guide": "level-3-tensor-memory.md",
        "architect_task": "Choose one physical tensor contract that balances accuracy, capacity, locality, parallelism, and conversion cost.",
        "reasoning_path": "access pattern → format/layout → placement/sharding → address proof → bytes and balance measurement",
        "decision": "How should logical values become physical pages, bank/core placements, and addresses?",
        "mechanism": "A composed format, page layout, memory layout, shard specification, allocation, and accessor contract.",
        "benefit": "Consumers receive engine-compatible data with predictable locality, parallelism, and address arithmetic.",
        "cost": "Padding, fragmentation, resharding, conversion, and scarce L1 capacity become first-class costs.",
        "evidence": "Exact byte footprints, boundary address derivations, per-bank/core balance, conversion counts, and measured movement stalls.",
        "paths": (
            "tensor_layouts/tensor_layouts.md",
            "data_formats/data_formats.md",
            "tensor_sharding/tensor_sharding.md",
            "memory/allocator.md",
            "tensor_accessor/tensor_accessor.md",
            "tensor_accessor/tensor_accessor_iterator.md",
            "prog_examples/pad_multi_core/pad_multi_core.md",
            "prog_examples/shard_data_rm/shard_data_rm.md",
        ),
    },
    {
        "number": 4,
        "slug": "kernels-dataflow",
        "title": "TT-Metal kernels and dataflow",
        "abstraction": "Low",
        "focus": "Host programs, reader/compute/writer kernels, NoC, and multicore flows.",
        "start_when": "you understand tensor storage and want to trace pages and tiles through actual device kernels",
        "guide": "level-4-kernels-dataflow.md",
        "architect_task": "Build a correct bounded reader–compute–writer pipeline and keep its limiting stage supplied.",
        "reasoning_path": "core ownership → input reuse → circular-buffer protocol → stage timeline → wait-state evidence",
        "decision": "Which core owns each output, and how do tiles move and change ownership without starving a stage?",
        "mechanism": "Reader–compute–writer kernels connected by circular-buffer and NoC completion protocols.",
        "benefit": "Movement overlaps compute while data reuse and multicast reduce external traffic.",
        "cost": "Loop counts, buffer capacity, semaphore state, and completion order become distributed correctness state.",
        "evidence": "Per-core ownership, CB state transitions, NoC barriers, stage timelines, and byte/reuse counts for one full block.",
        "paths": (
            "prog_examples/NoC_tile_transfer/NoC_tile_transfer.md",
            "prog_examples/multicast/multicast.md",
            "prog_examples/matmul_multi_core_optimized/data_reuse.md",
            "prog_examples/matmul_multi_core_optimized/data_mcast.md",
            "prog_examples/matmul_multi_core_optimized/matmul_multi_core_optimized.md",
            "prog_examples/sfpu_eltwise_chain/sfpu_eltwise_chain.md",
            "NamedKernelArgs/kernel_args_as_parameters.md",
            "code-indexing/kernel-code-indexing.md",
        ),
    },
    {
        "number": 5,
        "slug": "performance-debugging",
        "title": "Performance and debugging",
        "abstraction": "Advanced cross-layer",
        "focus": "Measure bottlenecks, debug kernels, and optimize with evidence.",
        "start_when": "a program is correct and you need to explain its latency, bandwidth, utilization, or failure mode",
        "guide": "level-5-performance-debugging.md",
        "architect_task": "Turn a symptom into a falsifiable bottleneck hypothesis and prove the optimization moved the critical path.",
        "reasoning_path": "metric → bounds → timeline/counters → competing hypotheses → one-variable experiment → correctness",
        "decision": "Which resource or control path is actually on the critical path?",
        "mechanism": "Bounds, synchronized host/device timelines, hardware counters, and controlled perturbation experiments.",
        "benefit": "Optimization effort targets the limiting mechanism and produces a reproducible causal explanation.",
        "cost": "Instrumentation perturbs execution and every result is scoped to workload, commit, architecture, and timing boundary.",
        "evidence": "A predicted counter/timeline response, one-variable experiment, end-to-end improvement, and unchanged correctness.",
        "paths": (
            "Debugging/Kernel_Debugging_Tips.md",
            "Debugging/DEVICE_PRINT_replaces_DPRINT.md",
            "op_kernel_dev/accuracy_tips/accuracy_tips.md",
            "MetalProfiler/metal-profiler.md",
            "real_time_profiler/getting-started.md",
            "PerfCounters/perf-counters.md",
            "PCIe_bandwidth/PCIe_bandwidth.md",
            "Saturating_DRAM_bandwidth/Saturating_DRAM_bandwidth.md",
            "GEMM_FLOPS/GEMM_FLOPS.md",
            "AdvancedPerformanceOptimizationsForModels/AdvancedPerformanceOptimizationsForModels.md",
        ),
    },
    {
        "number": 6,
        "slug": "distributed-systems",
        "title": "Multi-device and distributed systems",
        "abstraction": "Advanced system scale",
        "focus": "Meshes, Ethernet, collectives, fabric, and multi-host execution.",
        "start_when": "you can reason about one device and are ready to extend ownership, routing, and synchronization across devices or hosts",
        "guide": "level-6-distributed-systems.md",
        "architect_task": "Maintain global tensor meaning while mapping work, routes, events, and lifetimes onto a physical topology.",
        "reasoning_path": "global partition → rank/topology map → collective/link cost → ownership/events → per-rank critical path",
        "decision": "How should global work and state map onto meshes, hosts, routes, and collective schedules?",
        "mechanism": "Logical mesh abstractions lowered to topology-aware routing, transport, buffers, ranks, and events.",
        "benefit": "The same global program scales while communication can exploit physical locality and link concurrency.",
        "cost": "Stragglers, failure domains, congestion, teardown, and cross-rank ownership enter the correctness contract.",
        "evidence": "Global-to-physical maps, bytes per link, per-rank timelines, collective critical path, and explicit buffer state machines.",
        "paths": (
            "Programming_Mesh_of_Devices/Programming_Mesh_of_Devices_with_TT-NN.md",
            "Programming_Mesh_of_Devices/CCL_Performance_Best_Practices.md",
            "Programming_Multiple_Meshes/Programming_Multiple_Meshes.md",
            "EthernetMultichip/BasicEthernetGuide.md",
            "TT-Fabric/TT-Fabric-Architecture.md",
            "TT-Distributed/TT-Distributed-Architecture-1219.md",
            "TT-Distributed/MultiHostMeshRuntime.md",
            "TT-Distributed/HDSocketsModel.md",
            "TT-Distributed/TTMeshMigrationGuide.md",
        ),
    },
    {
        "number": 7,
        "slug": "hardware-isa",
        "title": "Hardware, TT-LLK, and ISA",
        "abstraction": "Lowest",
        "focus": "Tensix engines, formats at the hardware boundary, and architecture-specific details.",
        "start_when": "kernel-level behavior is no longer enough and you need to explain an engine, register, instruction, or architecture constraint",
        "guide": "level-7-hardware-isa.md",
        "architect_task": "Explain a localized engine-level limit without confusing documented behavior with inferred microarchitecture.",
        "reasoning_path": "localized symptom → supported API → TT-LLK → official ISA → microbenchmark → end-to-end proof",
        "decision": "Which engine, format, state transition, or instruction property explains the localized limit?",
        "mechanism": "Architecture-qualified TT-LLK/ISA semantics tested through minimal kernels and model-level validation.",
        "benefit": "Software can exploit native shapes, selectable precision, and specialized engines deliberately.",
        "cost": "The conclusion becomes generation-specific and inherits hazards, finite state, and numerical edge behavior.",
        "evidence": "An API-to-ISA call path, official source, isolated benchmark, counter/timeline signature, and upper-level impact.",
        "paths": (
            "matrix_engine/matrix_engine.md",
            "data_formats/reconfig_data_format.md",
            "data_formats/shared_exponent_precision_testing_suite/Readme.md",
            "Handling_Special_Value/special_values.md",
            "Blackhole/BlackholeBringUpProgrammingGuide.md",
        ),
    },
)


def report_paths() -> tuple[str, ...]:
    """Return every report path in curriculum order."""

    return tuple(path for layer in LAYERS for path in layer["paths"])
